#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   ./tools/run_screen_and_push.sh exp_autotune_phenotype
#
# What it does:
#   - Creates a new screen session: fuka6_<exp>_<stamp>
#   - Runs: ./tools/run_local.sh <exp>
#   - After completion:
#       - finds the newest runs/reports/<exp>_<stamp>.md (if present)
#       - commits and pushes it
#       - (optional) commits and pushes snapshot list file if present
#
# Notes:
#   - Blink SSH disconnect won't stop a screen session.
#   - run_local.sh already logs and can auto-push logs; this script also pushes the report.

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <experiment_module_name>"
  echo "Example: $0 exp_autotune_phenotype"
  exit 1
fi

EXP="$1"
STAMP="$(date -u +%Y%m%d_%H%M%S)"
SESSION="fuka6_${EXP}_${STAMP}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

mkdir -p runs/reports

# This is the command that will run inside screen.
# It runs the experiment via run_local.sh, then commits/pushes the report.
INNER_CMD=$(cat <<'EOF'
set -euo pipefail
EXP="__EXP__"
STAMP="__STAMP__"
ROOT="__ROOT__"
cd "$ROOT"

echo "[screen] Running experiment: $EXP  stamp=$STAMP"
./tools/run_local.sh "$EXP"

# Try to locate the matching report generated by the experiment (preferred)
REPORT="runs/reports/${EXP}_${STAMP}.md"

# If exact match not found (rare), fallback to newest report for this exp
if [[ ! -f "$REPORT" ]]; then
  REPORT="$(ls -t runs/reports/${EXP}_*.md 2>/dev/null | head -1 || true)"
fi

if [[ -n "${REPORT:-}" && -f "$REPORT" ]]; then
  echo "[screen] Found report: $REPORT"
  git add "$REPORT" || true
  git commit -m "Add ${EXP} report ${STAMP}" || true
  git push || true
  echo "[screen] Report pushed."
else
  echo "[screen] No report found to push."
fi

# Also add snapshot list if the experiment wrote one into NPZ field only,
# we don't have a separate file here. (If you later add a text snapshot index,
# add it here in the same pattern.)
echo "[screen] Done."
EOF
)

INNER_CMD="${INNER_CMD/__EXP__/$EXP}"
INNER_CMD="${INNER_CMD/__STAMP__/$STAMP}"
INNER_CMD="${INNER_CMD/__ROOT__/$ROOT}"

echo "Starting screen session: $SESSION"
echo "To attach later: screen -r $SESSION"
echo "To list screens: screen -ls"

# Start detached screen session
screen -dmS "$SESSION" bash -lc "$INNER_CMD"

echo "OK. Started: $SESSION"